# Generated by Django 5.2.7 on 2025-10-02 12:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatar', verbose_name='Avatar')),
                ('birth_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Birth Date')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('blood_group', models.CharField(blank=True, choices=[('na', 'NA'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('o+', 'O+'), ('o-', 'O-')], max_length=5, null=True, verbose_name='Blood Group')),
                ('acc_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_cameras', models.ManyToManyField(blank=True, related_name='Profile_assigned_cameras', to='app_devices.deviceinfo', verbose_name='Assigned Device')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '01. Profile',
                'verbose_name_plural': '01. Profiles',
            },
        ),
    ]
